name: Build and Run Example Project

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'          # Trigger workflow only if files in src directory change
      - 'pom.xml'         # Trigger workflow only if pom.xml file changes

env:
  smart-doc-version: ${{ github.run_id }} # Use the current GitHub workflow run ID as a temporary version number
  MAVEN_OPTS: "-Xms512m -Xmx1024m -Xss1024k"
jobs:
  build:
    if: ${{ github.event.pull_request.changed_files > 0 }} # Run this job only if there are file changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Create Logs Directory
        run: mkdir -p logs

      - name: Update Version in pom.xml
        run: mvn versions:set -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false

      - name: Build and Install Plugin
        run: |
          mvn install > logs/build.log 2>&1 || { cat logs/build.log; exit 1; }

      - name: Upload Plugin Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ~/.m2/repository/com/ly/smart-doc
          if-no-files-found: error

      - name: Upload Build Log
        if: failure()  # Only run if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: smart-doc-build-log
          path: logs

  maven-plugin-build:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: maven-plugin-build-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout Maven Plugin Repository
        uses: actions/checkout@v4
        with:
          repository: TongchengOpenSource/smart-doc-maven-plugin
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Create Logs Directory
        run: mkdir -p logs

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          mkdir -p ~/.m2/repository/com/ly/smart-doc
          echo "Overwriting target directory with new artifacts:"
          rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/ly/smart-doc

      - name: Update Version in pom.xml
        run: |
          mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false

      - name: Build and Install
        run: |
          mvn -DskipTests=true install > logs/install-plugin.log 2>&1 || { cat logs/install-plugin.log; exit 1; }

      - name: Upload Plugin Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: smart-doc-maven-plugin-jar
          path: ~/.m2/repository/com/ly/smart-doc
          if-no-files-found: error

      - name: Upload Plugin Build Log
        if: failure() # Only run if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: maven-plugin-build-logs
          path: logs

  generate-api-docs:
    needs: maven-plugin-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        doc_type: [ rest, dubbo, javadoc, websocket ]
    concurrency:
      group: generate-${{ matrix.doc_type }}-api-doc-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout Example Project
        uses: actions/checkout@v4
        with:
          repository: smart-doc-group/smart-doc-example-cn
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Logs Directory
        run: mkdir -p logs

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-plugin-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          mkdir -p ~/.m2/repository/com/ly/smart-doc
          echo "Overwriting target directory with new artifacts:"
          rsync -av --delete ./artifacts/ ~/.m2/repository/com/ly/smart-doc/
          echo "Listing files in target directory:"
          ls -lh ~/.m2/repository/com/ly/smart-doc

      - name: Update Smart-Doc Version in pom.xml
        run: |
          mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false

      - name: Build and Install Example Project
        run: |
          mvn -DskipTests=true install > logs/build-example-project.log 2>&1 || { cat logs/build-example-project.log; exit 1; }

      - name: Generate ${{ matrix.doc_type }} API Documentation
        run: |
          case ${{ matrix.doc_type }} in
            rest)
              mvn -DskipTests=true smart-doc:adoc > logs/rest-adoc.log 2>&1 || { cat logs/rest-adoc.log; exit 1; }
              mvn -DskipTests=true smart-doc:html > logs/rest-html.log 2>&1 || { cat logs/rest-html.log; exit 1; }
              mvn -DskipTests=true smart-doc:jmeter > logs/rest-jmeter.log 2>&1 || { cat logs/rest-jmeter.log; exit 1; }
              mvn -DskipTests=true smart-doc:markdown > logs/rest-markdown.log 2>&1 || { cat logs/rest-markdown.log; exit 1; }
              mvn -DskipTests=true smart-doc:openapi > logs/rest-openapi.log 2>&1 || { cat logs/rest-openapi.log; exit 1; } 
              mvn -DskipTests=true smart-doc:postman > logs/rest-postman.log 2>&1 || { cat logs/rest-postman.log; exit 1; }
              mvn -DskipTests=true smart-doc:word > logs/rest-word.log 2>&1 || { cat logs/rest-word.log; exit 1; } 
              mvn test -Dtest=com.power.doc.torna.TornaApiTest > logs/rest-TornaApiTest.log 2>&1 || { cat logs/rest-TornaApiTest.log; exit 1; } 
              ;;
            dubbo)
              mvn -DskipTests=true smart-doc:rpc-adoc > logs/dubbo-doc.adoc 2>&1 || { cat logs/dubbo-doc.adoc; exit 1; }
              mvn -DskipTests=true smart-doc:rpc-html > logs/dubbo-html.log 2>&1 || { cat logs/dubbo-html.log; exit 1; }
              mvn -DskipTests=true smart-doc:rpc-markdown > logs/dubbo-markdown.log 2>&1 || { cat logs/dubbo-markdown.log; exit 1; }
              ;;
            javadoc)
              mvn -DskipTests=true smart-doc:javadoc-adoc > logs/javadoc-adoc.log 2>&1 || { cat logs/javadoc-adoc.log; exit 1; }
              mvn -DskipTests=true smart-doc:javadoc-html > logs/javadoc-html.log 2>&1 || { cat logs/javadoc-html.log; exit 1; }
              mvn -DskipTests=true smart-doc:javadoc-markdown > logs/javadoc-markdown.log 2>&1 || { cat logs/javadoc-markdown.log; exit 1; }
              ;;
            websocket)
              mvn -DskipTests=true smart-doc:websocket-adocc > logs/websocket-adocc.log 2>&1 || { cat logs/websocket-adocc.log; exit 1; }
              mvn -DskipTests=true smart-doc:websocket-html > logs/websocket-html.log 2>&1 || { cat logs/websocket-html.log; exit 1; }
              mvn -DskipTests=true smart-doc:websocket-markdown > logs/websocket-markdown.log 2>&1 || { cat logs/websocket-markdown.log; exit 1; }
              ;;
          esac

      - name: Upload ${{ matrix.doc_type }} API Documentation
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.doc_type }}-api-doc
          path: ${{ github.workspace }}/target/doc/
          if-no-files-found: error

      - name: Upload API Documentation Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.doc_type }}-api-doc-log
          path: logs

  generate-grpc-api-doc:
    needs: maven-plugin-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    concurrency:
      group: generate-grpc-api-doc-${{ matrix.os }}-${{ github.event.pull_request.number }}
      cancel-in-progress: true

    steps:
      - name: Checkout Example Project
        uses: actions/checkout@v4
        with:
          repository: smart-doc-group/smart-doc-example-cn
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Logs Directory
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "macos-latest" ]]; then
            mkdir -p logs
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mkdir logs
          fi
        shell: bash

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: smart-doc-maven-plugin-jar
          path: ./artifacts

      - name: Move Files to Local Maven Repository
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" || "${{ matrix.os }}" == "macos-latest" ]]; then
            TARGET_DIR=~/.m2/repository/com/ly/smart-doc/
            mkdir -p "$TARGET_DIR" || echo "Directory already exists"
            rsync -av --delete ./artifacts/ "$TARGET_DIR"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            TARGET_DIR="$USERPROFILE\\.m2\\repository\\com\\ly\\smart-doc\\"
            mkdir -p "$TARGET_DIR" || echo "Directory already exists"
            cp -r ./artifacts/* "$TARGET_DIR"
          fi
        shell: bash


      - name: Update Smart-Doc Version in pom.xml
        run: |
          mvn versions:set-property -Dproperty="smart-doc.version" -DnewVersion="${{ env.smart-doc-version }}" -DgenerateBackupPoms=false

      - name: Build and Install Example Project
        run: |
          mvn -DskipTests=true install > build.log 2>&1 || { cat build.log; exit 1; }

      - name: Generate gRPC AsciiDoc Documentation
        run: | 
          mvn -DskipTests=true smart-doc:grpc-adoc > logs/grpc-adoc.log 2>&1 || { cat logs/grpc-adoc.log; exit 1; }

      - name: Generate gRPC HTML Documentation
        run: mvn -DskipTests=true smart-doc:grpc-html > logs/grpc-html.log 2>&1 || { cat logs/grpc-html.log; exit 1; }

      - name: Generate gRPC Markdown Documentation
        run: mvn -DskipTests=true smart-doc:grpc-markdown > logs/grpc-markdown.log 2>&1 || { cat logs/grpc-markdown.log; exit 1; }

      - name: Upload gRPC API Documentation
        uses: actions/upload-artifact@v4
        with:
          name: gRPC-api-doc-${{ runner.os }}
          path: ${{ github.workspace }}/target/doc/
          if-no-files-found: error

      - name: Upload API Documentation Log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: grpc-api-doc-log
          path: logs